name: 获取构建信息
description: 提取Git提交哈希、标签、构建时间戳，并生成适当的二进制文件名
inputs:
  goos:
    description: 目标操作系统
    required: true
  goarch:
    description: 目标架构
    required: true
  extension:
    description: 文件扩展名（例如，Windows上的.exe）
    required: false
    default: ""
  project-name:
    description: 项目名称
    required: false
    default: "MediaTools"
outputs:
  git-commit:
    description: Git commit 完整哈希值
    value: ${{ steps.build-info.outputs.git-commit }}
  version:
    description: 版本标签
    value: ${{ steps.build-info.outputs.version }}
  built-at:
    description: 构建时间
    value: ${{ steps.build-info.outputs.built-at }}
  filename:
    description: 生成的二进制文件名
    value: ${{ steps.build-info.outputs.filename }}

runs:
  using: "composite"
  steps:
    - name: Extract build information
      id: build-info
      shell: bash
      run: |
        git_commit=$(git rev-parse HEAD)
        git_commit_short=$(git rev-parse --short HEAD)
        version=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev-${git_commit_short}")
        built_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        filename="${{ inputs.project-name }}-${{ inputs.goos }}-${{ inputs.goarch }}${{ inputs.extension }}"

        echo "git-commit=$git_commit" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "built-at=$built_at" >> $GITHUB_OUTPUT
        echo "filename=$filename" >> $GITHUB_OUTPUT

        echo "🔍 Build Information:"
        echo "  Git Commit: $git_commit"
        echo "  version: $version"
        echo "  Built At: $built_at"
        echo "  Filename: $filename"
