definitions:
  config.CustomWordConfig:
    properties:
      customization:
        description: 自定义占位置词
        items:
          type: string
        type: array
      exclude_words:
        description: 自定义排除词
        items:
          type: string
        type: array
      identify_word:
        description: 自定义识别词
        items:
          type: string
        type: array
    type: object
  config.FanartConfig:
    properties:
      api_key:
        type: string
      api_url:
        type: string
      languages:
        description: 语言顺序
        items:
          type: string
        type: array
    type: object
  config.FormatConfig:
    properties:
      movie:
        description: 电影格式
        type: string
      tv:
        description: 电视剧格式
        type: string
    type: object
  config.LibraryConfig:
    properties:
      dst_path:
        description: 目标路径
        type: string
      dst_type:
        allOf:
        - $ref: '#/definitions/storage.StorageType'
        description: 目标类型
      name:
        description: 媒体库名称
        type: string
      organize_by_category:
        description: 是否按分类分文件夹
        type: boolean
      organize_by_type:
        description: 是否按类型分文件夹
        type: boolean
      src_path:
        description: 源路径
        type: string
      src_type:
        allOf:
        - $ref: '#/definitions/storage.StorageType'
        description: 源类型
      transfer_type:
        allOf:
        - $ref: '#/definitions/storage.TransferType'
        description: 传输类型
    type: object
  config.LogConfig:
    properties:
      console_level:
        description: 终端输出日志级别
        type: string
      file_dir:
        description: 日志文件目录
        type: string
      file_level:
        description: 文件日志级别
        type: string
    type: object
  config.TMDBConfig:
    properties:
      api_key:
        description: API Key
        type: string
      api_url:
        description: TMDB API URL
        type: string
      image_url:
        description: 图片 API URL
        type: string
      include_image_language:
        description: 包含的图片语言
        type: string
      language:
        description: 语言
        type: string
    type: object
  meta.MediaType:
    enum:
    - 0
    - 1
    - 2
    format: int32
    type: integer
    x-enum-comments:
      MediaTypeMovie: 电影
      MediaTypeTV: 电视剧
      MediaTypeUnknown: 未知
    x-enum-descriptions:
    - 未知
    - 电影
    - 电视剧
    x-enum-varnames:
    - MediaTypeUnknown
    - MediaTypeMovie
    - MediaTypeTV
  schemas.FileInfoRequest:
    properties:
      path:
        type: string
      storage_type:
        $ref: '#/definitions/storage.StorageType'
    required:
    - path
    - storage_type
    type: object
  schemas.LibraryArchiveMediaRequest:
    properties:
      dst_dir:
        $ref: '#/definitions/schemas.FileInfoRequest'
      scrape:
        type: boolean
      src_file:
        $ref: '#/definitions/schemas.FileInfoRequest'
      transfer_type:
        $ref: '#/definitions/storage.TransferType'
    required:
    - dst_dir
    - src_file
    type: object
  schemas.ScrapeRequest:
    properties:
      dst_file:
        $ref: '#/definitions/schemas.FileInfoRequest'
      media_type:
        $ref: '#/definitions/meta.MediaType'
      tmdb_id:
        type: integer
    required:
    - dst_file
    type: object
  storage.StorageType:
    enum:
    - 0
    - 1
    format: int32
    type: integer
    x-enum-comments:
      StorageLocal: 本地文件系统
      StorageUnknown: 未知文件系统
    x-enum-descriptions:
    - 未知文件系统
    - 本地文件系统
    x-enum-varnames:
    - StorageUnknown
    - StorageLocal
  storage.TransferType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    format: int32
    type: integer
    x-enum-comments:
      TransferCopy: 复制
      TransferLink: 硬链接
      TransferMove: 移动
      TransferSoftLink: 软链接
      TransferUnknown: 未知转移类型
    x-enum-descriptions:
    - 未知转移类型
    - 复制
    - 移动
    - 硬链接
    - 软链接
    x-enum-varnames:
    - TransferUnknown
    - TransferCopy
    - TransferMove
    - TransferLink
    - TransferSoftLink
info:
  contact: {}
  description: 下一代媒体刮削&整理工具
  title: MediaTools API 文档
  version: "1.0"
paths:
  /config/fanart:
    get:
      description: 获取 Fanart 配置
      produces:
      - application/json
      responses: {}
      summary: 获取 Fanart 配置
      tags:
      - 应用配置
      - Fanart
    post:
      consumes:
      - application/json
      description: 更新 Fanart 配置
      parameters:
      - description: Fanart 配置
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/config.FanartConfig'
      produces:
      - application/json
      responses: {}
      summary: 更新 Fanart 配置
      tags:
      - 应用配置
      - Fanart
  /config/libraries:
    get:
      description: 获取媒体库配置
      produces:
      - application/json
      responses: {}
      summary: 获取媒体库配置
      tags:
      - 应用配置
    post:
      consumes:
      - application/json
      description: 更新媒体库配置
      parameters:
      - description: 媒体库配置
        in: body
        name: config
        required: true
        schema:
          items:
            $ref: '#/definitions/config.LibraryConfig'
          type: array
      produces:
      - application/json
      responses: {}
      summary: 更新媒体库配置
      tags:
      - 应用配置
  /config/log:
    get:
      description: 获取日志配置
      produces:
      - application/json
      responses: {}
      summary: 获取日志配置
      tags:
      - 应用配置
      - 日志
    post:
      consumes:
      - application/json
      description: 更新日志配置
      parameters:
      - description: 日志配置
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/config.LogConfig'
      produces:
      - application/json
      responses: {}
      summary: 更新日志配置
      tags:
      - 应用配置
      - 日志
  /config/media/custom_word:
    get:
      consumes:
      - application/json
      description: 获取自定义词配置
      produces:
      - application/json
      responses: {}
      summary: 获取自定义词配置
      tags:
      - 应用配置
    post:
      consumes:
      - application/json
      description: 更新自定义词配置
      parameters:
      - description: 自定义词配置
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/config.CustomWordConfig'
      produces:
      - application/json
      responses: {}
      summary: 更新自定义词配置
      tags:
      - 应用配置
  /config/media/format:
    get:
      description: 获取媒体格式配置
      produces:
      - application/json
      responses: {}
      summary: 获取媒体格式配置
      tags:
      - 应用配置
    post:
      consumes:
      - application/json
      description: 更新媒体格式配置
      parameters:
      - description: 媒体格式配置
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/config.FormatConfig'
      produces:
      - application/json
      responses: {}
      summary: 更新媒体格式配置
      tags:
      - 应用配置
  /config/tmdb:
    get:
      description: 获取 TMDB 配置
      produces:
      - application/json
      responses: {}
      summary: 获取 TMDB 配置
      tags:
      - 应用配置
      - TMDB
    post:
      consumes:
      - application/json
      description: 更新 TMDB 配置
      parameters:
      - description: TMDB 配置
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/config.TMDBConfig'
      responses: {}
      summary: 更新 TMDB 配置
      tags:
      - 应用配置
      - TMDB
  /library/archive:
    post:
      consumes:
      - application/json
      description: 整理一个视频文件及其相关的字幕和音轨文件到指定目录
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.LibraryArchiveMediaRequest'
      produces:
      - application/json
      responses: {}
      summary: 归档媒体文件
      tags:
      - 媒体库
  /log/recent:
    get:
      description: 获取最近日志
      produces:
      - application/json
      responses: {}
      summary: 获取最近日志
      tags:
      - 日志
  /overview/{media_type}/{tmdb_id}:
    get:
      description: 根据媒体类型和 TMDB ID 获取对应的概述信息
      parameters:
      - description: 媒体类型
        enum:
        - Movie
        - TV
        in: path
        name: media_type
        required: true
        type: string
      - description: TMDB ID
        in: path
        name: tmdb_id
        required: true
        type: integer
      - description: 季数
        in: query
        name: season
        type: integer
      - description: 集数
        in: query
        name: episode
        type: integer
      responses: {}
      summary: 获取媒体概述信息
      tags:
      - TMDB
  /poster/{media_type}/{tmdb_id}:
    get:
      description: 根据媒体类型和 TMDB ID 获取对应的海报图片 URL
      parameters:
      - description: 媒体类型
        enum:
        - Movie
        - TV
        in: path
        name: media_type
        required: true
        type: string
      - description: TMDB ID
        in: path
        name: tmdb_id
        required: true
        type: integer
      responses: {}
      summary: 获取媒体海报图片
      tags:
      - TMDB
  /scrape/video:
    post:
      consumes:
      - application/json
      description: 刮削视频文件的元数据和相关信息
      parameters:
      - description: 刮削请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.ScrapeRequest'
      produces:
      - application/json
      responses: {}
      summary: 刮削视频
      tags:
      - 刮削
schemes:
- HTTP
swagger: "2.0"
