name: Binary Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

jobs:
  build-web:
    name: Build Web Frontend
    uses: ./.github/workflows/core/web.yaml

  build-binary:
    needs: build-web
    name: Build Binary
    uses: ./.github/workflows/core/binary.yaml
