name: Binary Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      NEED_BUILD_WEB:
        description: "是否需要构建前端"
        default: true
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      NEED_BUILD_WEB:
        description: "是否需要构建前端"
        default: true
        required: true
        type: boolean

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

jobs:
  build-web:
    if: ${{ inputs.NEED_BUILD_WEB == true || github.event_name == 'push' || github.event_name == 'pull_request' }}
    name: Build Web Frontend
    uses: ./.github/workflows/web-builder.yaml

  build-binary:
    needs: build-web
    name: Build Binary
    uses: ./.github/workflows/binary-builder-core.yaml
