name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            goos: linux
            goarch: amd64
          - platform: ubuntu-22.04-arm
            goos: linux
            goarch: arm64

          - platform: macos-latest
            goos: darwin
            goarch: amd64
          - platform: macos-latest
            goos: darwin
            goarch: arm64

          - platform: windows-latest
            goos: windows
            goarch: amd64
            extension: .exe
          # - platform: windows-11-arm
          #   goos: windows
          #   goarch: arm64
          #   extension: .exe

    name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Dependency
        if: matrix.goos == 'linux'
        run: |
          sudo bash scripts/linux.sh

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup web
        run: |
          cd web
          pnpm install
          pnpm run build
          cd ..

      - name: Build
        shell: bash
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          git_commit=$(git rev-parse HEAD)
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev-$git_commit")
          built_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          filename="MediaTools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}"

          go build -o "build/${filename}" \
            -s -w \
            -ldflags="-X MediaTools/internal/config.appVersion=$tag \
                      -X MediaTools/internal/config.commitHash=$git_commit \
                      -X MediaTools/internal/config.buildTime=$built_at" \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MediaTools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}
          path: build/MediaTools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }}
