name: Docker Builder

on:
  workflow_call:
    inputs:
      IS_LATEST:
        description: "是否发布为Docker镜像最新版本"
        required: true
        type: boolean
      NEED_BUILD_WEB:
        description: "是否需要构建前端"
        default: true
        required: true
        type: boolean
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      IS_LATEST:
        description: "是否发布为Docker镜像最新版本"
        default: false
        required: true
        type: boolean
      NEED_BUILD_WEB:
        description: "是否需要构建前端"
        default: true
        required: true
        type: boolean

env:
  IS_LATEST: ${{ inputs.IS_LATEST }}

jobs:
  build-web:
    if: ${{ inputs.NEED_BUILD_WEB == true }}
    name: Build Web Frontend
    uses: ./.github/workflows/web-builder.yaml

  build-docker:
    needs: build-web
    name: Build Docker Image
    uses: ./.github/workflows/docker-builder-core.yaml
    with:
      IS_LATEST: ${{ inputs.IS_LATEST }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
